server: 
  port: 9004
spring: 
  application:  
    name: newsblogsite-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.30.135:3306/newsblogsite_gathering?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true


jwt:
  config:
    key: NewsBlogSite
    ttl: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true