server:
  port: 9006
spring:
  application:
    name: newsblogsite-comment #指定服务名
  data:
    mongodb:
      host: 192.168.30.135
      database: commentdb
  redis:
    host: 192.168.30.135


jwt:
  config:
    key: NewsBlogSite
    ttl: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true